"""fix nullable pe checks, overall_coverage, uploaded_at

Revision ID: fb434bc9103f
Revises: de16635868ee
Create Date: 2026-07-08 18:44:51.710169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb434bc9103f'
down_revision: Union[str, Sequence[str], None] = 'de16635868ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.alter_column('coverpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('coverpoints', schema=None) as batch_op:
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('checks',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('overall_coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('overall_coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('checks',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('coverpoints', schema=None) as batch_op:
        batch_op.alter_column('coverage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
        batch_op.alter_column('run_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.alter_column('coverpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
